# Generated by Django 6.0.7 on 2026-08-01 06:10

import django.db.models.deletion
import statuspage.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("heartbeat", "0013_monitor_check_type_monitor_port_alter_monitor_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Service Status", max_length=200)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Shown below the title"),
                ),
                (
                    "logo_url",
                    models.URLField(blank=True, help_text="URL to your logo image"),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("minimal", "Minimal"),
                            ("corporate", "Corporate"),
                        ],
                        default="dark",
                        max_length=20,
                    ),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("list", "List View"),
                            ("grid", "Grid View"),
                            ("compact", "Compact"),
                        ],
                        default="list",
                        max_length=20,
                    ),
                ),
                (
                    "sort_order",
                    models.CharField(
                        choices=[
                            ("alpha", "Alphabetical"),
                            ("status", "Status (DOWN first)"),
                            ("manual", "Custom Order"),
                        ],
                        default="status",
                        max_length=20,
                    ),
                ),
                ("show_uptime", models.BooleanField(default=True)),
                ("show_response_time", models.BooleanField(default=True)),
                ("show_incidents", models.BooleanField(default=True)),
                ("show_timeline", models.BooleanField(default=True)),
                ("show_graph", models.BooleanField(default=False)),
                (
                    "header_color",
                    models.CharField(blank=True, default="#1a1a2e", max_length=7),
                ),
                (
                    "accent_color",
                    models.CharField(blank=True, default="#00d4aa", max_length=7),
                ),
                (
                    "custom_domain",
                    models.CharField(
                        blank=True,
                        help_text="e.g. status.yourdomain.com",
                        max_length=255,
                        null=True,
                        unique=True,
                        validators=[statuspage.models.validate_hostname],
                    ),
                ),
                ("domain_verified", models.BooleanField(default=False)),
                (
                    "domain_verification_token",
                    models.CharField(blank=True, max_length=64),
                ),
                ("domain_claimed_at", models.DateTimeField(blank=True, null=True)),
                ("dns_instructions", models.TextField(blank=True, editable=False)),
                ("meta_description", models.CharField(blank=True, max_length=300)),
                ("favicon_url", models.URLField(blank=True)),
                (
                    "footer_text",
                    models.CharField(
                        blank=True, default="Powered by PingPilot", max_length=500
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("password_protected", models.BooleanField(default=False)),
                ("access_password", models.CharField(blank=True, max_length=128)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_pages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatusPageIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("maintenance", "Scheduled Maintenance"),
                            ("investigating", "Investigating"),
                            ("identified", "Identified"),
                            ("monitoring", "Monitoring"),
                            ("resolved", "Resolved"),
                        ],
                        default="investigating",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_posts",
                        to="statuspage.statuspage",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="StatusPageMonitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Override the monitor name on this page",
                        max_length=200,
                    ),
                ),
                ("show_on_page", models.BooleanField(default=True)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_pages",
                        to="heartbeat.monitor",
                    ),
                ),
                (
                    "status_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitors",
                        to="statuspage.statuspage",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddIndex(
            model_name="statuspage",
            index=models.Index(fields=["slug"], name="statuspage__slug_16bad9_idx"),
        ),
        migrations.AddIndex(
            model_name="statuspage",
            index=models.Index(fields=["user"], name="statuspage__user_id_cbda24_idx"),
        ),
        migrations.AddIndex(
            model_name="statuspage",
            index=models.Index(
                fields=["custom_domain"], name="statuspage__custom__43a5ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="statuspage",
            index=models.Index(
                fields=["custom_domain", "domain_verified", "is_published"],
                name="statuspage__custom__70c556_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="statuspagemonitor",
            unique_together={("status_page", "monitor")},
        ),
    ]
