# Generated by Django 6.0.7 on 2026-07-24 16:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Monitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField()),
                (
                    "method",
                    models.CharField(
                        choices=[("GET", "Get"), ("HEAD", "Head")],
                        default="GET",
                        max_length=4,
                    ),
                ),
                ("expected_status", models.IntegerField(default=200)),
                (
                    "expected_keyword",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("timeout", models.IntegerField(default=10)),
                (
                    "check_interval_seconds",
                    models.PositiveIntegerField(
                        default=300,
                        validators=[
                            django.core.validators.MinValueValidator(180),
                            django.core.validators.MaxValueValidator(86400),
                        ],
                    ),
                ),
                (
                    "next_check_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("consecutive_failures", models.IntegerField(default=0)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_status",
                    models.CharField(
                        choices=[
                            ("UP", "Up"),
                            ("DOWN", "Down"),
                            ("DEGRADED", "Degraded"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("last_alert_sent_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField(blank=True)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indidents",
                        to="heartbeat.monitor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HeartBeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UP", "Up"),
                            ("DOWN", "Down"),
                            ("DEGRADED", "Degraded"),
                        ],
                        max_length=10,
                    ),
                ),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=200)),
                ("response_time_ms", models.FloatField(blank=True, null=True)),
                ("body_size", models.IntegerField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="heartbeats",
                        to="heartbeat.monitor",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="monitor",
            index=models.Index(
                fields=["next_check_at"], name="heartbeat_m_next_ch_25f357_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitor",
            index=models.Index(fields=["user"], name="heartbeat_m_user_id_5c5af4_idx"),
        ),
        migrations.AddIndex(
            model_name="incident",
            index=models.Index(
                fields=["monitor", "closed_at"], name="heartbeat_i_monitor_d9356c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="heartbeat",
            index=models.Index(
                fields=["monitor", "-checked_at"], name="heartbeat_h_monitor_25b124_idx"
            ),
        ),
    ]
