# Generated by Django 6.0.7 on 2026-07-25 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartbeat", "0002_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="name",
            field=models.CharField(default="Unnamed", max_length=100),
        ),
    ]
