# Generated by Django 6.0.7 on 2026-07-27 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartbeat", "0003_apikey_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="email_alerts",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="NotificationChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=50)),
                ("label", models.CharField(blank=True, max_length=50)),
                ("config", models.JSONField(default=dict)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channels",
                        to="heartbeat.monitor",
                    ),
                ),
            ],
            options={
                "ordering": ["provider"],
            },
        ),
    ]
