# Generated by Django 6.0.7 on 2026-07-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartbeat", "0004_monitor_email_alerts_notificationchannel"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="share_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
