# Generated by Django 6.0.7 on 2026-07-29 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartbeat", "0005_monitor_share_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[("down", "Down Alert"), ("up", "Recovery Alert")],
                        max_length=10,
                    ),
                ),
                (
                    "channel",
                    models.CharField(blank=True, default="email", max_length=50),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_logs",
                        to="heartbeat.monitor",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
    ]
