# Generated by Django 6.0.7 on 2026-07-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartbeat", "0007_backfill_alertlogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="group",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="monitor",
            name="ssl_alert_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
