# Generated by Django 6.0.7 on 2026-07-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartbeat", "0008_monitor_group_monitor_ssl_alert_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="headers",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
