# Generated by Django 6.0.7 on 2026-07-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartbeat", "0009_monitor_headers"),
    ]

    operations = [
        migrations.AddField(
            model_name="heartbeat",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
