# Generated by Django 6.0.7 on 2026-07-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartbeat", "0011_apirequestlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationchannel",
            name="provider",
            field=models.CharField(
                blank=True,
                choices=[
                    ("webhook", "Webhook"),
                    ("telegram", "Telegram"),
                    ("discord", "Discord"),
                    ("slack", "Slack"),
                    ("teams", "Microsoft Teams"),
                    ("pushover", "Pushover"),
                    ("googlechat", "Google Chat"),
                    ("mattermost", "Mattermost"),
                    ("zulip", "Zulip"),
                    ("pagerduty", "PagerDuty"),
                    ("ntfy", "ntfy"),
                    ("gotify", "Gotify"),
                    ("rocketchat", "Rocket.Chat"),
                    ("zapier", "Zapier"),
                    ("make", "Make"),
                    ("n8n", "n8n"),
                    ("ifttt", "IFTTT"),
                    ("chime", "Amazon Chime"),
                    ("matrix", "Matrix"),
                    ("signl4", "SIGNL4"),
                    ("xmatters", "xMatters"),
                    ("opsgenie", "Opsgenie"),
                    ("splunk", "Splunk On-Call"),
                    ("github", "GitHub"),
                ],
                max_length=50,
            ),
        ),
    ]
