# Generated by Django 6.0.7 on 2026-07-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("heartbeat", "0012_alter_notificationchannel_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitor",
            name="check_type",
            field=models.CharField(
                choices=[("http", "HTTP(S)"), ("tcp", "TCP Port")],
                default="http",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="monitor",
            name="port",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="url",
            field=models.CharField(max_length=500),
        ),
    ]
