# Generated by Django 6.0.7 on 2026-07-31 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_telegramconnection"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="monthly_report",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="weekly_report",
            field=models.BooleanField(default=True),
        ),
    ]
