# Generated by Django 6.0.7 on 2026-07-31 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_monthly_report_profile_weekly_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="auto_refresh",
            field=models.BooleanField(default=False),
        ),
    ]
